Repository 42Statistics/42Stat-Backend, pull requests merged in 2023-06, with the labels that each got.

#117 style 🎨 naming
  app/src/api/coalitionsUser/coalitionsUser.service.ts
  app/src/api/cursusUser/cursusUser.service.ts
  app/src/dateRange/dateRange.service.ts
  app/src/page/home/home.service.ts
  app/src/page/personalGeneral/personal.general.resolver.ts
  app/src/page/personalGeneral/personal.general.service.ts
  app/src/util/time.ts
Labels: enhancement

#124 fix: :bug: leaderboard 에서 사용하는 타입을 UserRanking => LeaderboardRanking …
  app/src/page/leaderboard/eval/leaderboard.eval.service.ts
  app/src/page/leaderboard/exp/leaderboard.exp.service.ts
  app/src/page/leaderboard/level/leaderboard.level.service.ts
  app/src/page/leaderboard/models/leaderboard.model.ts
  app/src/page/leaderboard/score/leaderboard.score.service.ts
  app/src/page/leaderboard/util/leaderboard.util.service.ts
  app/src/schema.gql
Labels: bug

#128 refactor: :recycle: Object Time => Class StatDate
  app/src/api/coalitionsUser/coalitionsUser.service.ts
  app/src/api/cursusUser/cursusUser.service.ts
  app/src/api/location/location.service.ts
  app/src/dateRange/dateRange.service.ts
  app/src/page/home/coalition/home.coalition.service.ts
  app/src/page/home/user/home.user.service.ts
  app/src/page/personal/general/personal.general.service.ts
  app/src/statDate/StatDate.ts
  app/src/util/index.ts
Labels: enhancement

#143 feat: :sparkles: user team info 추가
  app/src/api/project/db/project.database.aggregate.ts
  app/src/api/project/project.service.ts
  app/src/api/team/db/team.database.schema.ts
  app/src/api/team/team.module.ts
  app/src/api/team/team.service.ts
  app/src/page/personal/general/models/personal.general.model.ts
  app/src/page/personal/general/personal.general.module.ts
  app/src/page/personal/general/personal.general.service.ts
  app/src/schema.gql
Labels: enhancement

#147 feat: :sparkles: landing page 제작
  app/package.json
  app/src/app.module.ts
  app/src/page/landing/landing.module.ts
  app/src/page/landing/landing.resolver.ts
  app/src/page/landing/landing.service.ts
  app/src/page/landing/models/landing.model.ts
  app/src/schema.gql
Labels: enhancement

#159 fix 🐛 dependency
  app/src/api/experienceUser/experienceUser.module.ts
  app/src/page/evalLog/evalLog.module.ts
  app/src/page/home/coalition/home.coalition.module.ts
  app/src/page/home/eval/home.eval.module.ts
  app/src/page/home/user/home.user.module.ts
  app/src/page/landing/landing.module.ts
  app/src/page/leaderboard/eval/leaderboard.eval.module.ts
  app/src/page/leaderboard/exp/leaderboard.exp.module.ts
  app/src/page/leaderboard/level/leaderboard.level.module.ts
  app/src/page/leaderboard/score/leaderboard.score.module.ts
  app/src/page/myInfo/myInfo.module.ts
  app/src/page/myInfo/myInfo.service.ts
  app/src/page/personal/eval/personal.eval.module.ts
  app/src/page/personal/general/personal.general.module.ts
Labels: bug

#163 feat ✨ score cache
  app/src/api/score/score.cache.service.ts
  app/src/api/score/score.module.ts
  app/src/page/home/coalition/home.coalition.service.ts
  app/src/page/leaderboard/score/leaderboard.score.cache.service.ts
  app/src/page/leaderboard/score/leaderboard.score.module.ts
  app/src/page/leaderboard/score/leaderboard.score.service.ts
  app/src/page/myInfo/myInfo.service.ts
Labels: enhancement

#165 feat ✨ exp cache
  app/src/api/experienceUser/experienceUser.cache.service.ts
  app/src/api/experienceUser/experienceUser.module.ts
  app/src/api/scaleTeam/scaleTeam.cache.service.ts
  app/src/api/score/score.cache.service.ts
  app/src/page/leaderboard/exp/leaderboard.exp.cache.service.ts
  app/src/page/leaderboard/exp/leaderboard.exp.module.ts
  app/src/page/leaderboard/exp/leaderboard.exp.service.ts
  app/src/page/myInfo/myInfo.service.ts
Labels: enhancement

#166 fix: :bug: bucket 에서 default 값에 대해 적절히 처리되지 않는 오류 수정
  app/src/api/cursusUser/cursusUser.service.ts
  app/src/common/db/common.db.aggregation.ts
  app/src/statDate/StatDate.ts
Labels: bug

#185 fix: :bug: rank값 id에서 실제 exam rank로 바꾸기
  app/src/api/team/team.service.ts
  app/src/page/home/team/home.team.service.ts
Labels: bug

#186 refactor ♻️ cache
  app/package.json
  app/pnpm-lock.yaml
  app/src/api/cursusUser/cursusUser.cache.service.ts
  app/src/api/cursusUser/cursusUser.module.ts
  app/src/api/experienceUser/db/experiecneUser.database.aggregate.ts
  app/src/api/experienceUser/experienceUser.cache.service.ts
  app/src/api/experienceUser/experienceUser.module.ts
  app/src/api/location/location.cache.service.ts
  app/src/api/scaleTeam/db/scaleTeam.database.aggregate.ts
  app/src/api/scaleTeam/scaleTeam.cache.service.ts
  app/src/api/scaleTeam/scaleTeam.module.ts
  app/src/api/score/db/score.database.aggregate.ts
  app/src/api/score/score.cache.service.ts
  app/src/api/score/score.module.ts
  app/src/api/score/score.service.ts
  app/src/cache/cache.service.ts
  app/src/cache/inMemory/cache.inMemory.service.ts
  app/src/common/models/common.user.model.ts
  app/src/dateRange/dateRange.service.ts
  app/src/page/home/coalition/home.coalition.service.ts
  app/src/page/home/eval/home.eval.service.ts
  app/src/page/home/user/home.user.module.ts
  app/src/page/home/user/home.user.service.ts
  app/src/page/leaderboard/eval/leaderboard.eval.module.ts
  app/src/page/leaderboard/eval/leaderboard.eval.service.ts
  app/src/page/leaderboard/exp/leaderboard.exp.module.ts
  app/src/page/leaderboard/exp/leaderboard.exp.service.ts
  app/src/page/leaderboard/leaderboard.ranking.args.ts
  app/src/page/leaderboard/level/leaderboard.level.module.ts
  app/src/page/leaderboard/level/leaderboard.level.service.ts
  app/src/page/leaderboard/score/leaderboard.score.module.ts
  app/src/page/leaderboard/score/leaderboard.score.service.ts
  app/src/page/myInfo/myInfo.service.ts
  app/src/page/personal/eval/personal.eval.service.ts
  app/src/page/personal/general/personal.general.module.ts
  app/src/page/personal/general/personal.general.resolver.ts
  app/src/page/personal/general/personal.general.service.ts
  app/src/redis/redis.module.ts
  app/src/redis/redis.util.service.ts
  docker-compose.yml
  redis/Dockerfile
  redis/entry.sh
  redis/redis-log/.gitkeep
  redis/redis.conf
Labels: bug, enhancement

#192 feat: ✨ destiny user rank
  app/src/api/scaleTeam/scaleTeam.service.ts
  app/src/api/team/team.service.ts
  app/src/page/personal/eval/models/personal.eval.model.ts
  app/src/page/personal/eval/personal.eval.module.ts
  app/src/page/personal/eval/personal.eval.resolver.ts
  app/src/page/personal/eval/personal.eval.service.ts
  app/src/schema.gql
Labels: enhancement

#201 fix: :bug: logtime service 버그 수정
  app/src/api/location/location.service.ts
Labels: bug
