Repository 42Statistics/42Stat-Backend, pull requests merged in 2023-08, with the labels that each got.

#273 fix: 🐛 pageInfo type 이 불필요하게 nullable 이였던 문제 수정
  app/src/pagination/cursor/models/pagination.cursor.model.ts
Labels: bug

#279 feat: :sparkles: team info 에 user 추가 정보, finalMark 추가
  app/src/api/team/team.service.ts
  app/src/page/teamInfo/models/teamInfo.model.ts
  app/src/schema.gql
Labels: enhancement

#283 feat: :sparkles: team info 에서 last event time 을 추가
  app/src/api/team/team.service.ts
  app/src/page/teamInfo/models/teamInfo.model.ts
  app/src/schema.gql
Labels: enhancement

#284 fix: :bug: project info 에서 circle 의 gql schema 가 nullable 하지 않던 문제 수정
  app/src/api/location/location.service.ts
  app/src/page/personal/general/models/personal.general.model.ts
  app/src/page/projectInfo/models/projectInfo.model.ts
  app/src/schema.gql
Labels: bug

#285 refactor: ♻️ coalition score record 가 이번 달 점수를 포함해서 반환하도록 변경
  app/src/api/score/score.service.ts
  app/src/lambda/lambda.service.ts
  app/src/page/home/coalition/home.coalition.service.ts
Labels: enhancement

#292 refactor: :recycle: search module => page/spotlight, lib/regexFind 로 분리, user 검색 시 소문자 자동변환 추가
  app/src/app.module.ts
  app/src/lib/regexFind/regexFind.module.ts
  app/src/lib/regexFind/regexFind.service.ts
  app/src/page/evalLog/evalLog.module.ts
  app/src/page/evalLog/evalLog.service.ts
  app/src/page/search/search.resovler.ts
  app/src/page/search/search.service.ts
  app/src/page/spotlight/dtos/spotlight.dto.getSpotlight.ts
  app/src/page/spotlight/models/spotlight.model.ts
  app/src/page/spotlight/spotlight.module.ts
  app/src/page/spotlight/spotlight.resovler.ts
  app/src/page/spotlight/spotlight.service.ts
  app/src/schema.gql
Labels: bug, enhancement

#294 style: :art: recentExamResult 의 인자 이름을 after => skip 으로 변경
  app/src/page/home/team/dtos/home.team.dto.recentExamResultArgs.ts
  app/src/page/home/team/home.team.resolver.ts
  app/src/page/home/team/home.team.service.ts
  app/src/schema.gql
Labels: enhancement

#304 build: :recycle: github action 수정
  .github/workflows/cicd.yml
Labels: bug, enhancement

#318 fix: :bug: teamCLoseRecords 에서 시험 제외
  app/src/page/home/team/home.team.service.ts
Labels: bug
